# SECK Mouhamadou Abdoulaye
# abdouseck.tiv@gmail.com

In [2]:
import gensim
import os 

1) Chargement des données textuelles

In [3]:
path='Data/'
l=[]
for rep in os.listdir(path):
    for fichier in os.listdir(path+rep):
        print(rep,fichier)
        with open(path+rep+'/'+fichier,'r',encoding="utf8") as f:
            l.append(f.read().replace('\n\n','.').replace('\n',' ').strip())

Guerre combat 49586-0.txt
Guerre combat about_homme_oreille_cassee.txt
Histoires andersen_contes_tome2.txt
Histoires Candide.txt
Histoires Carroll-Alice_au_Pays_des_Merveilles.txt
Histoires clint_eastwood.txt
Histoires hugo_les_miserables_fantine.txt
Histoires jules_verne_20000_lieues_sous_les_mers.txt
Histoires jules_verne_de_la_terre_a_la_lune.txt
Histoires L'école des femmes.txt
Histoires la_bible_nouveau_testament.txt
Histoires le_petit_prince.txt
Histoires mille_et_une_nuits_t1.txt
Histoires mille_et_une_nuits_t2.txt
Histoires mille_et_une_nuits_t3.txt
Histoires stevenson_ile_au_tresor.txt
Histoires st_exupery_le_petit_prince.txt
roman Adelaide
roman aimard_aigle_noir_dacotahs.txt
roman ayme-nain.txt
roman Blemont-contes.txt
roman dumas_monte_cristo_1.txt
roman dumas_monte_cristo_2.txt
roman dumas_monte_cristo_3.txt
roman dumas_monte_cristo_4.txt
roman Emile zola.txt
roman L'élixir de longue vie.txt
roman La fille aux yeux d'or.txt
roman Le chef-d'oeuvre inconnu .txt
roman Le colo

2) Le nettoyage

Tokens (dont ponctuation de fin de phrase) / stop words 



In [4]:
import re


def tok_me(texte):
    # Je modifie la chaine de caractere s'il y a une ponctuation
    texte=texte.replace('.',' . ').replace('!', ' ! ').replace('?', ' ? ')
    p="([aA-zZéèàùîêâûôçïëœ.!?-]{1,})"
    texte=' '.join(re.findall(p,texte))
    #Je renvoi une liste de token
    return texte.split()

with open('stop-w_fr.txt',"r",encoding='utf8') as f:
    stop=f.read().split('\n')
stop.remove('haut')
stop.remove('pas')
stop.remove('ne')
stop.remove('n')
stop.remove('ni')
stop.remove('peu')
stop.remove('bon')
stop.remove('très')
stop.remove('tres')
stop.remove('même')
stop.remove('fait')
stop.remove('début')
stop.remove('mais')
stop.remove('dès')
stop.remove('premier')
stop.remove('première')
stop.remove('plus')
stop.remove('aussi')
stop.remove('bien')
stop.remove('assez')
stop.remove('retour')
stop.remove('tout')
stop.remove('rien')

def stop_me(liste_token):
    final=[]
    for token in liste_token:
        if token in stop:
            continue
        final.append(token)
    return final



stop_me(tok_me(l[0]))

['.',
 '.',
 'Quel',
 'Art',
 'gens-là',
 '?',
 'Et',
 'bien',
 'faire',
 'artistes',
 'signataires',
 '_Appel',
 'monde',
 'civilisé_',
 'remplacer',
 'patrimoine',
 'esthétique',
 'hommes',
 'merveilles',
 'biffées',
 'portail',
 'Reims',
 '--je',
 'veux',
 'Behrens',
 'Klinger',
 'Stuck',
 'Trubner',
 'Hildebrand',
 'aînés',
 'signataires',
 'même',
 'manifeste',
 'Hans',
 'Thoma',
 'Gebhardt',
 'Kaulbach',
 'Kalkreuth',
 'Liebermann',
 'Defregger',
 '?',
 'Beaucoup',
 'ne',
 'soupçonnaient',
 'pas',
 'existence',
 'viennent',
 'révéler',
 'procédé',
 'infaillible',
 'suffragette',
 'lacéra',
 '_Vénus',
 'miroir_',
 'vagabond',
 'déroba',
 '_Joconde_',
 '.',
 'C',
 'notoriété',
 'n',
 'pas',
 'gloire',
 'demeure',
 'ébahi',
 'prestesse',
 'acquérir',
 '.',
 'Il',
 'ouvriers',
 'cherchent',
 'faire',
 'connaître',
 'production',
 'œuvre',
 'monde',
 'surpris',
 'n',
 'connu',
 'noms',
 'destruction',
 'chef-d',
 'œuvre',
 '.',
 '.',
 'Mais',
 'tout',
 'ne',
 'pas',
 'lacérer',
 'toil

3) Decoupage en phrase

liste=[phrase 1, phrase 2, phrase3, phrase N] (où N est le nombre de phrase de tous les textes)
et phrase 1 = [mot1,mot2, ...,motn] (où n est le nombre de mot de la phrase 1)

In [5]:
l[0]

'..Quel est l’Art de ces gens-là? Et qu’ont bien pu faire les artistes, signataires de l’_Appel au monde civilisé_, pour remplacer, dans le patrimoine esthétique des hommes, les merveilles qu’ils ont biffées du portail de Reims,--je veux dire les Behrens, les Klinger, les Stuck, les Trubner, les Hildebrand, sans parler de leurs aînés, signataires du même manifeste, les Hans Thoma, les Gebhardt, les Kaulbach, les Kalkreuth, les Liebermann, les Defregger? Beaucoup de gens ne soupçonnaient pas leur existence; ils viennent de la révéler par un procédé infaillible: celui de cette suffragette qui lacéra la _Vénus au miroir_, ou de ce vagabond qui déroba la _Joconde_. C’est de la notoriété, si ce n’est pas de la gloire, et l’on demeure ébahi de leur prestesse à l’acquérir. Il y a des ouvriers qui cherchent à se faire connaître par la production de quelque œuvre: le monde surpris n’a connu les noms de ceux-là que par la destruction d’un chef-d’œuvre..Mais comme, après tout, il ne suffit pas de

In [6]:
def cut_sent(tokens):
    final=[]
    tmp=[]
    for tok in tokens:
        if tok in [".","!","?"]:
            if tmp != []:
                final.append(tmp)
            tmp=[]
        else:
            tmp.append(tok)
    if tmp != []:
        final.append(tmp)
    return final

cut_sent(stop_me(tok_me(l[0])))

[['Quel', 'Art', 'gens-là'],
 ['Et',
  'bien',
  'faire',
  'artistes',
  'signataires',
  '_Appel',
  'monde',
  'civilisé_',
  'remplacer',
  'patrimoine',
  'esthétique',
  'hommes',
  'merveilles',
  'biffées',
  'portail',
  'Reims',
  '--je',
  'veux',
  'Behrens',
  'Klinger',
  'Stuck',
  'Trubner',
  'Hildebrand',
  'aînés',
  'signataires',
  'même',
  'manifeste',
  'Hans',
  'Thoma',
  'Gebhardt',
  'Kaulbach',
  'Kalkreuth',
  'Liebermann',
  'Defregger'],
 ['Beaucoup',
  'ne',
  'soupçonnaient',
  'pas',
  'existence',
  'viennent',
  'révéler',
  'procédé',
  'infaillible',
  'suffragette',
  'lacéra',
  '_Vénus',
  'miroir_',
  'vagabond',
  'déroba',
  '_Joconde_'],
 ['C',
  'notoriété',
  'n',
  'pas',
  'gloire',
  'demeure',
  'ébahi',
  'prestesse',
  'acquérir'],
 ['Il',
  'ouvriers',
  'cherchent',
  'faire',
  'connaître',
  'production',
  'œuvre',
  'monde',
  'surpris',
  'n',
  'connu',
  'noms',
  'destruction',
  'chef-d',
  'œuvre'],
 ['Mais',
  'tout',
 

Generalisation sur tous les livres

In [8]:
from tqdm import tqdm

final=[]
for livre in tqdm(l):
    final=final+cut_sent(stop_me(tok_me(livre)))
    

100%|██████████████████████████████████████████████████████████████████████████████████| 71/71 [03:17<00:00,  2.78s/it]


4) Construire un modèle type Word2Vec avec gensim

In [9]:
from gensim.models import Word2Vec

model = Word2Vec(sentences=final, vector_size=50, window=5)
model.save("word2vec.model")

5) Qualification du modele

In [10]:
model.wv.get_vector('Christ')

array([-1.083708  , -0.6734484 ,  1.203562  ,  1.799621  , -0.12014043,
        0.45180115, -0.28653648,  1.0687271 , -1.0343094 ,  0.2880688 ,
        0.48315665, -0.528293  , -0.09236894, -0.44821078,  1.0934056 ,
       -2.0456758 ,  1.6604958 , -0.27010047, -0.9684351 ,  0.08479243,
       -0.12278994,  1.0928807 ,  0.14804707, -1.1139362 ,  0.8965652 ,
       -2.0416849 ,  0.06945604,  0.06881464,  0.15043093,  0.04588203,
        0.5867603 ,  0.4147507 ,  1.1455723 ,  0.48982757, -0.8563975 ,
       -1.2315468 ,  1.188141  ,  0.945019  ,  0.94207585, -0.1074113 ,
        0.49721688,  1.2509449 , -1.9471753 , -1.785195  , -0.3987443 ,
        1.1616067 , -0.4758263 , -1.3841559 ,  0.7407147 ,  1.162647  ],
      dtype=float32)

In [11]:
model.wv.most_similar('Christ')

[('Dieu', 0.8952490091323853),
 ('Seigneur', 0.8878018260002136),
 ('Père', 0.8782588839530945),
 ('Jésus', 0.8739196062088013),
 ('Fils', 0.8580815196037292),
 ('Esprit', 0.8529345393180847),
 ('prophètes', 0.8514426946640015),
 ('gloire', 0.8505409955978394),
 ('évangile', 0.8465577363967896),
 ('prophète', 0.8372992277145386)]

In [12]:
model.wv.most_similar('Jésus')

[('Seigneur', 0.9266344904899597),
 ('Père', 0.8875834941864014),
 ('Juifs', 0.877235472202301),
 ('Christ', 0.8739196062088013),
 ('Esprit', 0.8715451955795288),
 ('disciples', 0.8679142594337463),
 ('Fils', 0.861926794052124),
 ('croyants', 0.8397989869117737),
 ('Fernand', 0.8345863223075867),
 ('Lantenac', 0.8337613940238953)]

In [13]:
model.wv.most_similar('Marseille')

[('Paris', 0.8344871401786804),
 ('quitté', 0.7929524183273315),
 ('Jérusalem', 0.7923046946525574),
 ('Syrie', 0.7601670622825623),
 ('Toulon', 0.7536302208900452),
 ('Berlin', 0.7498263120651245),
 ('Renault', 0.7467765212059021),
 ('Sevran', 0.7464989423751831),
 ('Bonaparte', 0.7422492504119873),
 ('gypte', 0.7421019077301025)]

In [14]:
model.wv.most_similar('jeux')

[('jeu', 0.8257147669792175),
 ('hippiques', 0.7269940972328186),
 ('joueurs', 0.7155530452728271),
 ('cartes', 0.7139294147491455),
 ('ordinateur', 0.681290864944458),
 ('commandes', 0.6735735535621643),
 ('sports', 0.6733928322792053),
 ('machines', 0.6733310222625732),
 ('jouer', 0.6716527938842773),
 ('instruments', 0.6695637106895447)]

In [15]:
model.wv.most_similar(positive=['roi']+['femme'], negative=['homme'])

[('reine', 0.8148657083511353),
 ('sœur', 0.72672438621521),
 ('épouser', 0.7190898060798645),
 ('père', 0.7160548567771912),
 ('fils', 0.698328971862793),
 ('princesse', 0.6952990889549255),
 ('Beaujeu', 0.6933881640434265),
 ('sultan', 0.6899319887161255),
 ('gypte', 0.6895262598991394),
 ('Jeanne', 0.6880884766578674)]

In [16]:
model.wv.most_similar(positive=['Dieu']+['corps'], negative=['esprit'])

[('sang', 0.5850822925567627),
 ('démons', 0.5410383939743042),
 ('Christ', 0.5294321179389954),
 ('morts', 0.5217054486274719),
 ('chair', 0.5160072445869446),
 ('anges', 0.5042569041252136),
 ('vivant', 0.48342180252075195),
 ('abatteur', 0.48332029581069946),
 ('Seigneur', 0.48190298676490784),
 ('occipital', 0.4769934415817261)]

In [17]:
model.wv.vectors

array([[-0.9781213 ,  0.16522095,  3.2385907 , ..., -2.8462257 ,
         0.37821406, -1.8546113 ],
       [-0.364744  , -2.1696305 ,  1.6916089 , ..., -3.7046676 ,
         0.5331037 , -0.8191199 ],
       [-0.0209346 , -2.2615652 ,  2.3050542 , ..., -2.0096745 ,
        -0.08256624,  0.8402322 ],
       ...,
       [-0.07308458,  0.02065217, -0.02033376, ..., -0.04848434,
         0.05917469, -0.01313761],
       [-0.03629719,  0.0040739 ,  0.02316456, ..., -0.07172047,
        -0.01198681, -0.00393327],
       [-0.02060251,  0.04030681, -0.00831746, ...,  0.00728511,
         0.02770706, -0.06844134]], dtype=float32)

Text feat

In [18]:
import numpy as np

def sent_enc(chaine):
    summy=np.zeros(50)
    i=0
    for token in stop_me(tok_me(chaine)):
        try:
            summy=model.wv.get_vector(token)+summy
            i=i+1
        except:
            continue
    return summy / i


text1 = "Olympique de Marseille peut se targuer d’avoir pu compter sur Didier Drogba, Steve Mandanda, Dimitri Payet ou Franck Ribéry"

sent_enc(text1)

array([ 0.15765947,  0.03572176, -0.30348611,  0.04396695,  0.07338506,
        0.00972512,  0.16249436,  0.28884487, -0.06233805, -0.31507679,
       -0.01370485, -0.47262856,  0.36137835,  0.23245887, -0.03059068,
       -0.04103546,  0.17775602,  0.29984302, -0.39755372, -0.66929217,
        0.07437799,  0.52651511,  0.31410419, -0.19360156,  0.14195231,
        0.12552694, -0.13538761,  0.01128217,  0.13275723, -0.04139679,
        0.39843007, -0.13801233,  0.60306824,  0.55160963, -0.18365626,
        0.03461275,  0.27165556, -0.0720166 ,  0.1040061 , -0.16470565,
       -0.20175481,  0.22328673, -0.43878833,  0.10439887,  0.44107644,
       -0.24006967, -0.1727942 , -0.16983438,  0.40407362,  0.24178812])

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

theme=['sport',"football",'jeux','télévision','cinéma','amour']
text1 = "Olympique de Marseille peut se targuer d’avoir pu compter sur Didier Drogba, Steve Mandanda, Dimitri Payet ou Franck Ribéry"
d={}

for th in theme :
    print(th)
    print(cosine_similarity(sent_enc(text1).reshape(1,-1),model.wv.get_vector(th).reshape(1,-1))[0][0])
    print('############################')
    d[th]=cosine_similarity(sent_enc(text1).reshape(1,-1),model.wv.get_vector(th).reshape(1,-1))[0][0]
    
d

sport
0.12131270851334205
############################
football
0.42628186173134863
############################
jeux
0.11954480787318313
############################
télévision
0.14632531606627575
############################
cinéma
0.18591562960856012
############################
amour
-0.05127910433069369
############################


{'sport': 0.12131270851334205,
 'football': 0.42628186173134863,
 'jeux': 0.11954480787318313,
 'télévision': 0.14632531606627575,
 'cinéma': 0.18591562960856012,
 'amour': -0.05127910433069369}